spring:
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/2024-06-wanted-market
    username: root
    password: root1234!!

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    root: INFO

jwt:
  secret-key: ${jwt-secret-key}
  access-token-plus-hour: ${jwt-access-token-plus-hour}
